#Minecraft Server Properties
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=true
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
send-minecraft-usage-stats=false
player-idle-timeout=0
difficulty=normal
spawn-monsters=true
broadcast-op-messages=true
pvp=true
snooper-enabled=true
level-type=minecraft\:normal
hardcore=false
enable-status=true
enable-rcon=false
force-gamemode=false
network-compression-threshold=256
max-tick-time=60000
use-native-transport=true
max-players=20
online-mode=true
enable-trust=false
server-ip=
spawn-npcs=true
allow-flight=false
server-port=25565
view-distance=10
resource-pack-prompt=
spawn-animals=true
white-list=false
rcon.password=
spawn-protection=16
max-world-size=29999984
